language: haskell

sudo: required

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.4],  sources: [hvr-ghc]}}
  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev libgtksourceview-3.0-dev libwebkitgtk-3.0-dev

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal update
  - cabal install -j4 Cabal cabal-install
  - hash -r
  - cabal --version
  - cabal install -j4 gtk2hs-buildtools
  - cabal install -j4 ./ vendor/gi-gtk-hs vendor/ltk vendor/leksah-server vendor/haskellVCSWrapper/vcswrapper vendor/haskellVCSGUI/vcsgui ghcjs-dom --enable-tests --only-dependencies --force-reinstalls
  - cabal install vendor/gi-gtk-hs vendor/ltk vendor/leksah-server vendor/haskellVCSWrapper/vcswrapper vendor/haskellVCSGUI/vcsgui

script:
  - cabal configure --enable-tests -v2
  - cabal build
  - cabal test
  - cabal sdist

notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
