resolver: lts-7.2
packages:
- '.'
- 'vendor/leksah-server'
- 'vendor/ltk'
- 'vendor/haskellVCSGUI/vcsgui'
- 'vendor/yi'
- 'vendor/haskellVCSWrapper/vcswrapper'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- binary-shared-0.8.3
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsaddle-0.3.1.0
- gi-gtk-hs-0.3.1.0
- gi-gtksource-3.0.6
- gi-javascriptcore-3.0.6
- gi-soup-2.4.6
- gi-webkit-3.0.6
- jsaddle-0.4.0.5
- jsaddle-dom-0.2.0.1
- gi-gdk-3.0.6
- gi-gdkpixbuf-2.0.6
- gi-glib-2.0.6
- gi-gobject-2.0.6
- gi-gtk-3.0.6
- gi-cairo-1.0.6
- gi-gio-2.0.6
- gi-pango-1.0.6

# Override default flag values for local packages and extra-deps
flags:
  gi-cairo:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gdk:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gdkpixbuf:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gio:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-glib:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gobject:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gtk:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gtk-hs:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-gtksource:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-javascriptcore:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-pango:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-soup:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true
  gi-webkit:
    overloaded-methods: true
    overloaded-signals: true
    overloaded-properties: true

# Extra package databases containing global packages
extra-package-dbs: []