flags: {}
packages:
- '.'
extra-deps:
- binary-shared-0.8.3
- ghcjs-codemirror-0.0.0.1
- ghcjs-dom-0.2.1.0
- gtk3-mac-integration-0.3.2.0
- gtksourceview3-0.13.2.0
- jsaddle-0.2.1.0
- regex-tdfa-text-1.0.0.3
- leksah-server-0.15.0.8
- ltk-0.15.0.4
- vado-0.0.5
- vcsgui-0.1.3.0
- vcswrapper-0.1.2
- webkitgtk3-0.14.1.0
- webkitgtk3-javascriptcore-0.13.1.0
- gtk2hs-buildtools-0.13.0.4
- gtk3-0.14.1
resolver: lts-3.1
